go_version: "1.21.5"
go_tarball: "go{{ go_version }}.linux-amd64.tar.gz"
go_download_url: "https://go.dev/dl/{{ go_tarball }}"
go_install_path: "/usr/local/go"
go_bin_path: "/usr/local/go/bin"
goose_version: v3.18.0