---
- name: Restart OpenVPN
  ansible.builtin.systemd:
    name: openvpn
    enabled: true
    state: restarted

- name: Restart nftables
  service:
    name: nftables
    state: restarted

- name: Restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
