---
- name: Restart OpenVPN
  ansible.builtin.systemd:
    name: openvpn
    # state: reloaded
    state: restarted
    daemon-reload: true

- name: Restart nftables
  service:
    name: nftables
    state: restarted

- name: Restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
