---
# - name: Build docker image
#   hosts: docker_build_host
#   become: true
#   roles:
#     - common
#     - docker
#     - build

# - name: 1C web server in docker container
#   hosts: 1c-mega
#   become: true
#   roles:
    # - common
    # - docker
    # - loading_image
    # - 1c

- name: Pull Base from server
  hosts: mega-fvds
  become: true
  roles:
    - common
    - 1c_base_pull

- name: Push Base to server
  hosts: mega-office
  become: true
  roles:
    - common
    - 1c_base_push
