---
- name: Build docker image
  hosts: docker_build_host
  become: true
  roles:
    - common
    - docker
    - build
  tags: build

- name: Pull Base from server
  hosts: mega-fvds
  become: true
  roles:
    - common
    - 1c_base_pull
  tags: pull

- name: Push Base to server
  hosts: 1c-mega
  become: true
  roles:
    - common
    - 1c_base_push
  tags: push

- name: 1C web server in docker container
  hosts: 1c-mega
  become: true
  roles:
    - common
    - docker
    - security
    - samba
    - pptp
    - loading_image
    - 1c
  tags: 1c
