- name: create build directory
  file:
    path: "{{ group_vars.build.dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: copy tarball to host
  copy:
    src: "./soft{{ group_vars.build.image_name }}_{{ group_vars.build.version1c }}.tar"
    dest: "{{ group_vars.build.dir }}/{{ group_vars.build.image_name }}_{{ group_vars.build.version1c }}.tar"

- name: load container from tarball
  docker_image:
    name: "{{ group_vars.build.image_name }}:{{ group_vars.build.version1c }}"
    load_path: "{{ group_vars.build.dir }}/{{ group_vars.build.image_name }}_{{ group_vars.build.version1c }}.tar"
    state: present
    source: load