---
- name: create {{ host_vars.dir }} directory
  file:
    path: "{{ host_vars.dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: copy {{ group_vars.image_name }}_{{ group_vars.version1c }}.tar to host 1C
  copy:
    src: "./soft/{{ group_vars.image_name }}_{{ group_vars.version1c }}.tar"
    dest: "{{ host_vars.dir }}/{{ group_vars.image_name }}_{{ group_vars.version1c }}.tar"

- name: load container from tarball
  docker_image:
    name: "{{ group_vars.image_name }}:{{ group_vars.version1c }}"
    load_path: "{{ host_vars.dir }}/{{ group_vars.image_name }}_{{ group_vars.version1c }}.tar"
    state: present
    source: load
