---
- name: nftables | Load nftables config
  ansible.builtin.template:
    src: templates/nftables.conf.j2
    dest: /etc/nftables.conf
    mode: '0644'
  notify:
    - Restart nftables
    - Restart fail2ban
