---
- name: Update apt and install samba
  ansible.builtin.apt:
    name:
      - samba
      - samba-client
    state: latest
    update_cache: yes

- name: Создание директорий для шар
  file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: '0777'
  loop: "{{ samba_shares }}"

- name: config_samba | configuring samba
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart smbd

- name: Добавление Samba пользователей
  user:
    name: "{{ item.name }}"
    state: present
    shell: /usr/sbin/nologin
  loop: "{{ samba_users }}"

- name: Установка паролей для Samba пользователей
  command: >
    smbpasswd -a -s {{ item.name }}
  args:
    stdin: "{{ item.password }}\n{{ item.password }}\n"
  loop: "{{ samba_users }}"
  notify:
    - Restart smbd
