---
- name: Update apt and install samba
  ansible.builtin.apt:
    name:
      - samba
      - samba-client
    state: latest

- name: create {{ host_vars.smbdir }} directory
  file:
    path: "{{ host_vars.smbdir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: config_samba | configuring samba
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart smbd