---
- name: create {{ host_vars.dir }} directory
  file:
    path: "{{ host_vars.dir }}/1c/{{ item.name }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop: "{{ host_vars.containers }}"

- name: copy db files - 1Cv8.1CD.zip
  copy:
    src: "./db_pp/{{ item.name }}/1Cv8.1CD.zip"
    dest: "{{ host_vars.dir }}/1c/{{ item.name }}/1Cv8.1CD.zip"
    owner: root
    group: root
    mode: '0777'
  loop: "{{ host_vars.containers }}"
  ignore_errors: yes

- name: Unarchive 1Cv8.1CD.zip
  ansible.builtin.unarchive:
    src: "{{ host_vars.dir }}/1c/{{ item.name }}/1Cv8.1CD.zip"
    dest: "{{ host_vars.dir }}/1c/{{ item.name }}"
    extra_opts: "-j"
    remote_src: yes
  loop: "{{ host_vars.containers }}"

- name: Remove arhive 1Cv8.1CD.zip
  ansible.builtin.file:
    path: "{{ host_vars.dir }}/1c/{{ item.name }}/1Cv8.1CD.zip"
    state: absent
  loop: "{{ host_vars.containers }}"

- name: Create container
  community.docker.docker_container:
    name: "{{ item.name }}"
    image: "{{ group_vars.image_name }}:{{ group_vars.version1c }}"
    restart_policy: "unless-stopped"
    volumes:
      - "{{ host_vars.dir }}/1c/{{ item.name }}:/1c/{{ item.name }}:rw"
    ports:
      - "192.168.10.102:{{ item.ports }}:80" # 0.0.0.0:9000:8000
  loop: "{{ host_vars.containers }}"
