---
- name: Install packages using apt
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - python3-pip
      - python3-setuptools
      - virtualenv
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - pipx
    state: latest
    update_cache: true
    install_recommends: false

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present

- name: Update apt and install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - python3-docker
    state: latest
  notify:
    - Restart docker

- name: Run and enable docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
