openvpn_dir: "/etc/openvpn"
openvpn_cert_dir: "/etc/openvpn/server"
easy_rsa_dir: "/usr/share/easy-rsa" # whereis easy-rsa
client_config_dir: "/tmp/openvpn_clients"
vpn_server_address: "{{ vault_secrets.mega.ak_vpn_ip }}"
vpn_protocol: "udp"
vpn_port: 1194
users:
  - name: "user1"
  - name: "user2"