---
ssh_port: 22
openvpn_dir: "/etc/openvpn"
openvpn_cert_dir: "/etc/openvpn/server"
easy_rsa_dir: "/usr/share/easy-rsa" # whereis easy-rsa
client_config_dir: "/storage/openvpn_clients"
vpn_server_address: "{{ vault_secrets.mega.ak_vpn_ip }}"
vpn_protocol: "tcp"
vpn_port: 443
vpn_pool: 192.168.172.0
users:
  - name: "user1"
vpn_bot:
  dir: /storage/vpn-bot
  telegram_token: "{{ vault_secrets.vpnbot.telegram_token }}"
  admin_id: "{{ vault_secrets.vpnbot.admin_id }}"