- name: Include openvpn.yml
  ansible.builtin.include_tasks: openvpn.yml

- name: Include gateway.yml
  ansible.builtin.include_tasks: gateway.yml

# - name: Include fail2ban.yml
#   ansible.builtin.include_tasks: fail2ban.yml